version: '3.4'

services:
  svghai:
    image: svghai
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8012:8012
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
